# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Cross-validation tests comparing earth2bufr against pybufrkit references.

Each ``.bufr`` fixture in ``test/data/`` has a companion ``.ref.json``
generated by ``generate_references.py``.  These tests decode the same BUFR
file with earth2bufr and compare the output value-by-value.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from earth2bufr._decoder import decode
from earth2bufr._descriptors import expand_descriptors
from earth2bufr._reader import read_messages
from earth2bufr._section import parse_message
from earth2bufr._tables import TableSet

DATA_DIR = Path(__file__).parent / "data"

# Fixtures paired with known limitations
FIXTURE_INFO: dict[str, dict] = {
    "profiler_european.bufr": {"xfail": False, "reason": ""},
    "207003.bufr": {"xfail": False, "reason": ""},
    "uegabe.bufr": {
        "xfail": False,
        "reason": "",
    },
    "g2nd_208.bufr": {
        "xfail": False,
        "reason": "",
    },
    "b005_89.bufr": {
        "xfail": False,
        "reason": "",
    },
}


def _fixture_ids() -> list[str]:
    """Return list of fixture filenames that have .bufr files."""
    ids = []
    for fname in FIXTURE_INFO:
        bufr_path = DATA_DIR / fname
        if bufr_path.exists():
            ids.append(fname)
    return ids


def _load_reference(fname: str) -> list[dict]:
    """Load the .ref.json for a fixture.

    Raises
    ------
    pytest.skip
        If the reference file does not exist (e.g. oversized files
        excluded from version control).
    """
    ref_path = DATA_DIR / Path(fname).with_suffix(".ref.json")
    if not ref_path.exists():
        pytest.skip(f"Reference file not found: {ref_path.name}")
    return json.loads(ref_path.read_text(encoding="utf-8"))


def _decode_with_earth2bufr(
    fname: str,
) -> list[list[tuple[int, float | str | None]]]:
    """Decode a BUFR fixture using earth2bufr and return per-subset values.

    Returns a list of subsets, each subset is a list of (fxy_int, value) tuples.
    """
    bufr_path = DATA_DIR / fname
    raw = bufr_path.read_bytes()

    messages = list(read_messages(raw))
    assert len(messages) >= 1, f"No messages found in {fname}"

    msg = messages[0]
    parsed = parse_message(msg)

    tables = TableSet(
        centre=parsed.identification.originating_center,
        local_table_version=parsed.identification.local_table_version,
    )
    expanded = expand_descriptors(parsed.data_description.descriptors, tables)

    subsets = decode(
        expanded,
        parsed.data_bytes,
        parsed.identification.num_subsets,
        parsed.identification.compressed,
    )

    result: list[list[tuple[int, float | str | None]]] = []
    for subset in subsets:
        pairs: list[tuple[int, float | str | None]] = []
        for desc, val in subset.values:
            # Skip synthetic associated-field descriptors (fxy=999999)
            if desc.fxy == 999999:
                continue
            # Skip zero-width operator markers (222-237)
            if desc.entry.bit_width == 0:
                continue
            pairs.append((desc.fxy, val))
        result.append(pairs)
    return result


def _is_missing_string(val: str) -> bool:
    """Check if a string represents a BUFR missing indicator.

    pybufrkit decodes all-0xFF bytes as replacement characters (U+FFFD)
    rather than None. This helper detects such strings.
    """
    return all(c in ("\xff", "\ufffd", " ", "\x00") for c in val) and len(val) > 0


def _compare_values(
    actual: float | str | None,
    expected: float | str | None,
    tol: float = 1e-6,
) -> bool:
    """Compare a single decoded value against the reference.

    Parameters
    ----------
    actual : float | str | None
        Value from earth2bufr.
    expected : float | str | None
        Value from pybufrkit reference.
    tol : float
        Relative tolerance for numeric comparison.
    """
    if actual is None and expected is None:
        return True
    # Handle the all-0xFF string case: earth2bufr returns None,
    # pybufrkit returns replacement characters.
    if actual is None and isinstance(expected, str) and _is_missing_string(expected):
        return True
    if expected is None and isinstance(actual, str) and _is_missing_string(actual):
        return True
    if actual is None or expected is None:
        return False
    if isinstance(actual, str) and isinstance(expected, str):
        return actual == expected
    if isinstance(actual, int | float) and isinstance(expected, int | float):
        if expected == 0:
            return abs(actual) < tol
        return abs(actual - expected) / max(abs(expected), 1e-15) < tol
    # Type mismatch
    return False


@pytest.mark.crossval
@pytest.mark.parametrize("fname", _fixture_ids())
def test_crossval(fname: str) -> None:
    """Cross-validate earth2bufr output against pybufrkit reference."""
    info = FIXTURE_INFO.get(fname, {"xfail": False})
    if info.get("xfail"):
        pytest.xfail(info.get("reason", "Known limitation"))

    ref_data = _load_reference(fname)
    actual_subsets = _decode_with_earth2bufr(fname)

    assert len(actual_subsets) == len(
        ref_data
    ), f"Subset count mismatch: got {len(actual_subsets)}, expected {len(ref_data)}"

    mismatches: list[str] = []
    for rec in ref_data:
        subset_idx = rec["subset"]
        ref_values = rec["values"]
        actual_pairs = actual_subsets[subset_idx]

        # Filter out special pybufrkit descriptors (negative FXY = associated/stats)
        # and F=2 operator descriptors (222000-237255 = QC/bitmap operators)
        filtered_ref: list[list] = [
            pair
            for pair in ref_values
            if pair[0] >= 0 and not (200000 <= pair[0] < 300000)
        ]

        if len(actual_pairs) != len(filtered_ref):
            mismatches.append(
                f"Subset {subset_idx}: value count mismatch: got {len(actual_pairs)}, expected {len(filtered_ref)}"
            )
            # Still compare what we can
            compare_len = min(len(actual_pairs), len(filtered_ref))
        else:
            compare_len = len(actual_pairs)

        for i in range(compare_len):
            actual_fxy, actual_val = actual_pairs[i]
            ref_fxy, ref_val = filtered_ref[i]

            if actual_fxy != ref_fxy:
                mismatches.append(
                    f"Subset {subset_idx}[{i}]: descriptor mismatch: got {actual_fxy:06d}, expected {ref_fxy:06d}"
                )
                continue

            if not _compare_values(actual_val, ref_val):
                mismatches.append(
                    f"Subset {subset_idx}[{i}] desc={actual_fxy:06d}: "
                    f"value mismatch: got {actual_val!r}, expected {ref_val!r}"
                )

    if mismatches:
        detail = "\n".join(mismatches[:50])
        total = len(mismatches)
        pytest.fail(
            f"{total} mismatches in {fname}:\n{detail}"
            + (f"\n... and {total - 50} more" if total > 50 else "")
        )
