# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# %%
"""
CBottle Super Resolution
========================

Climate in a Bottle (cBottle) super resolution workflows for global weather.

This example will demonstrate the cBottle diffusion model for super resolution of global
weather data. The CBottleSR model takes low-resolution climate data and generates
high-resolution outputs using a diffusion-based approach.

For more information on cBottle see:

- https://arxiv.org/abs/2505.06474v1

In this example you will learn:

- Performing super resolution on synthetic data from the cBottle data source
- Performing super resolution on ERA5 data after infilling with cBottle
- Post-processing and visualizing super-resolution results
"""

# /// script
# dependencies = [
#   "earth2studio[cbottle,viz] @ git+https://github.com/NVIDIA/earth2studio.git",
# ]
# ///

# %%
# Set Up
# ------
# For this example we will use the cBottle data source, infill diagnostic, and the
# CBottleSR super resolution model. The workflow demonstrates two approaches:
#
# 1. Super resolution on synthetic data generated by cBottle3D
# 2. Super resolution on real ERA5 data after variable infilling

# %%
# We need the following components:
#
# - Datasource: Generate data from the CBottle3D data api :py:class:`earth2studio.data.CBottle3D`.
# - Datasource: Pull data from the WeatherBench2 data api :py:class:`earth2studio.data.WB2ERA5`.
# - Diagnostic Model: Use the built in CBottle Infill Model :py:class:`earth2studio.models.dx.CBottleInfill`.
# - Super Resolution Model: Use the CBottleSR super resolution model :py:class:`earth2studio.models.dx.CBottleSR`.

# %%

import os

os.makedirs("outputs", exist_ok=True)
from dotenv import load_dotenv

load_dotenv()  # TODO: make common example prep function

import torch

from earth2studio.data import WB2ERA5, CBottle3D, fetch_data
from earth2studio.models.dx import CBottleInfill, CBottleSR

# Get the device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Load the cBottle data source
package = CBottle3D.load_default_package()
cbottle_ds = CBottle3D.load_model(package)

# Load the super resolution model
super_resolution_window = (
    0,
    -120,
    50,
    -40,
)  # (lat south, lon west, lat north, lon east)
package = CBottleSR.load_default_package()
cbottle_sr = CBottleSR.load_model(
    package,
    output_resolution=(1024, 1024),
    super_resolution_window=super_resolution_window,
    distilled_model=True,
)

# Load the infill model
input_variables = ["u10m", "v10m"]
package = CBottleInfill.load_default_package()
cbottle_infill = CBottleInfill.load_model(
    package, input_variables=input_variables, sampler_steps=18
)

# Load the ERA5 data source
era5_ds = WB2ERA5()

# %%
# Super Resolution on Synthetic Data
# ----------------------------------
# First, let's generate synthetic climate data using the cBottle3D data source
# and then perform super resolution on it. This demonstrates the full cBottle
# pipeline from data generation to super-resolution enhancement.

# %%

import datetime

import numpy as np

from earth2studio.utils.coords import map_coords

times = np.array([datetime.datetime(2020, 1, 1)], dtype="datetime64[ns]")

# Generate some samples from cBottle
cbottle_ds = cbottle_ds.to(device)
synth_x, synth_coords = fetch_data(
    cbottle_ds,
    times,
    cbottle_sr.input_coords()["variable"],
    device=device,
)
del cbottle_ds  # Clean up data source model to free GPU memory

# Perform super resolution on synthetic data
cbottle_sr = cbottle_sr.to(device)
synth_x, synth_coords = map_coords(synth_x, synth_coords, cbottle_sr.input_coords())
sr_synth_x, sr_synth_coords = cbottle_sr(synth_x, synth_coords)

# %%
# Super Resolution on ERA5 Data
# -----------------------------
# Next, we'll demonstrate super resolution on real ERA5 data. Since ERA5 doesn't
# contain all the variables needed by CBottleSR, we first use the CBottleInfill
# model to predict the missing variables, then perform super resolution.

# %%

# Get the ERA5 data (only u10m and v10m available)
era5_x, era5_coords = fetch_data(
    era5_ds,
    times,
    input_variables,
    device=device,
)

# Perform infilling to get all required variables
cbottle_infill = cbottle_infill.to(device)
infill_x, infill_coords = cbottle_infill(era5_x, era5_coords)
del cbottle_infill  # Clean up infill model to free GPU memory

# Select the required variables and reshape for super resolution
infill_x, infill_coords = map_coords(infill_x, infill_coords, cbottle_sr.input_coords())
sr_infill_x, sr_infill_coords = cbottle_sr(infill_x, infill_coords)

# %%
# Post Processing CBottle Super Resolution Data
# ---------------------------------------------
# Let's visualize the super resolution results to compare the synthetic data
# approach with the ERA5 infilling approach. We'll plot the total cloud liquid
# water (tclw) variable as an example.

# %%
from earth2studio import viz


def _as_numpy(value):
    return value.cpu().numpy() if hasattr(value, "cpu") else value


viz.save_raster_grid(
    [
        viz.raster_panel(
            viz.raster_dataarray(
                synth_x[0, 0, 3, :, :].cpu().numpy(),
                lat=_as_numpy(synth_coords["lat"]),
                lon=_as_numpy(synth_coords["lon"]),
                name="u10m",
                attrs={"units": "m/s"},
            ),
            title="Synthetic Data (cBottle3D, low resolution)",
            colormap="RdBu_r",
            vmin=-20,
            vmax=20,
            colorbar_label="u10m (m/s)",
        ),
        viz.raster_panel(
            viz.raster_dataarray(
                sr_synth_x[0, 0, 3, :, :].cpu().numpy(),
                lat=_as_numpy(sr_synth_coords["lat"]),
                lon=_as_numpy(sr_synth_coords["lon"]),
                name="u10m",
                attrs={"units": "m/s"},
            ),
            title="Synthetic Data Super Resolution (cBottle3D to CBottleSR)",
            colormap="RdBu_r",
            vmin=-20,
            vmax=20,
            colorbar_label="u10m (m/s)",
        ),
        viz.raster_panel(
            viz.raster_dataarray(
                era5_x[0, 0, 0, :, :].cpu().numpy(),
                lat=_as_numpy(era5_coords["lat"]),
                lon=_as_numpy(era5_coords["lon"]),
                name="u10m",
                attrs={"units": "m/s"},
            ),
            title="ERA5 Data (low resolution)",
            colormap="RdBu_r",
            vmin=-20,
            vmax=20,
            colorbar_label="u10m (m/s)",
        ),
        viz.raster_panel(
            viz.raster_dataarray(
                sr_infill_x[0, 0, 3, :, :].cpu().numpy(),
                lat=_as_numpy(sr_infill_coords["lat"]),
                lon=_as_numpy(sr_infill_coords["lon"]),
                name="u10m",
                attrs={"units": "m/s"},
            ),
            title="ERA5 Infilled Super Resolution (ERA5 to CBottleInfill to CBottleSR)",
            colormap="RdBu_r",
            vmin=-20,
            vmax=20,
            colorbar_label="u10m (m/s)",
        ),
    ],
    "outputs/16_cbottle_super_resolution.jpg",
    ncols=2,
    figsize=(24, 24),
    dpi=150,
    bbox_inches="tight",
)
