# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Cross-validation tests comparing earth2bufrio against eccodes references.

Each ``.bufr`` fixture in ``tests/data/`` has a companion
``.eccodes.ref.json`` generated by ``generate_eccodes_references.py``.
These tests decode the same BUFR file with earth2bufrio and compare the
output value-by-value against the eccodes reference, using FXY descriptor
codes as the bridge between the two naming schemes.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import TYPE_CHECKING

import pytest

if TYPE_CHECKING:
    import pyarrow as pa  # type: ignore[import-untyped]

try:
    import eccodes  # noqa: F401

    HAS_ECCODES = True
except ImportError:
    HAS_ECCODES = False


DATA_DIR = Path(__file__).parent / "data"

# eccodes uses very large negative sentinel for BUFR missing values
_ECCODES_MISSING_THRESHOLD = -1e30

# Known decoder differences tracked but not failing the test.
# Maps filename -> {(msg_idx, subset_idx, fxy): "reason"}
_KNOWN_DIFFS: dict[str, dict[tuple[int, int, int], str]] = {
    "207003.bufr": {
        # earth2bufrio compressed-data decoder does not yet differentiate
        # per-subset values for some descriptors; eccodes correctly returns
        # per-subset arrays.
        (0, 0, 1033): "compressed per-subset value not yet split",
        # Replicated channel radiance list length differs due to replication
        # factor handling in compressed data.
        (0, 0, 14044): "replicated descriptor count differs in compressed data",
        (0, 1, 14044): "replicated descriptor count differs in compressed data",
    },
}

# Fixtures with known status
WORKING_FIXTURES = [
    "profiler_european.bufr",
    "207003.bufr",
    "uegabe.bufr",
]

XFAIL_FIXTURES = [
    pytest.param(
        "g2nd_208.bufr",
        marks=pytest.mark.xfail(
            reason=(
                "eccodes unrolls bitmap-qualified data (operators 224/236) "
                "into repeated descriptor instances; earth2bufrio emits "
                "substituted values as separate descriptors"
            ),
            strict=False,
        ),
    ),
    pytest.param(
        "b005_89.bufr",
        marks=pytest.mark.xfail(
            reason=(
                "eccodes unrolls bitmap-qualified data (operators 222/224/236/237) "
                "into repeated descriptor instances; earth2bufrio emits "
                "QC/substitution values as separate descriptors"
            ),
            strict=False,
        ),
    ),
]


def _load_eccodes_ref(fname: str) -> dict:
    """Load the .eccodes.ref.json for a fixture.

    Raises
    ------
    pytest.skip
        If the reference file does not exist (e.g. oversized files
        excluded from version control).
    """
    stem = Path(fname).stem
    ref_path = DATA_DIR / f"{stem}.eccodes.ref.json"
    if not ref_path.exists():
        pytest.skip(f"eccodes reference file not found: {ref_path.name}")
    return json.loads(ref_path.read_text(encoding="utf-8"))


def _normalize_missing(val: object) -> object:
    """Normalise eccodes missing-value sentinels to None.

    eccodes represents BUFR missing values as very large negative
    numbers (typically around -1e100). This function converts those
    sentinels to ``None`` so they can be compared against earth2bufrio's
    ``None`` representation.
    """
    if isinstance(val, float) and (val < _ECCODES_MISSING_THRESHOLD or math.isnan(val)):
        return None
    if isinstance(val, list):
        return [_normalize_missing(v) for v in val]
    return val


def _compare_scalar(
    actual: float | str | None,
    expected: float | str | None,
    tol: float = 1e-6,
) -> bool:
    """Compare two scalar values with tolerance.

    Parameters
    ----------
    actual : float | str | None
        Value from earth2bufrio.
    expected : float | str | None
        Value from eccodes reference (already normalised).
    tol : float
        Relative tolerance for numeric comparison.

    Returns
    -------
    bool
        True if values match within tolerance.
    """
    # Treat empty/whitespace-only strings as None
    if isinstance(actual, str) and actual.strip() == "":
        actual = None
    if isinstance(expected, str) and expected.strip() == "":
        expected = None
    if actual is None and expected is None:
        return True
    if actual is None or expected is None:
        return False
    if isinstance(actual, str) and isinstance(expected, str):
        return actual.strip() == expected.strip()
    if isinstance(actual, int | float) and isinstance(expected, int | float):
        fa, fe = float(actual), float(expected)
        if math.isnan(fa) and math.isnan(fe):
            return True
        if fe == 0:
            return abs(fa) < tol
        return abs(fa - fe) / max(abs(fe), 1e-15) < tol
    return False


def _compare_values(
    actual: object,
    expected: object,
    tol: float = 1e-6,
) -> tuple[bool, str]:
    """Compare earth2bufrio value against eccodes reference value.

    Handles scalars, lists (replicated descriptors), and None.

    Returns
    -------
    tuple[bool, str]
        (match, detail) where detail describes any mismatch.
    """
    if actual is None and expected is None:
        return True, ""

    # Both lists — compare element-by-element
    if isinstance(actual, list) and isinstance(expected, list):
        if len(actual) != len(expected):
            return (
                False,
                f"list length mismatch: got {len(actual)}, expected {len(expected)}",
            )
        for i, (a, e) in enumerate(zip(actual, expected, strict=True)):
            if not _compare_scalar(a, e, tol):
                return False, f"list[{i}]: got {a!r}, expected {e!r}"
        return True, ""

    # Scalar comparison
    if not isinstance(actual, list) and not isinstance(expected, list):
        if _compare_scalar(actual, expected, tol):  # type: ignore[arg-type]
            return True, ""
        return False, f"got {actual!r}, expected {expected!r}"

    # Type mismatch (list vs scalar)
    return (
        False,
        f"type mismatch: got {type(actual).__name__}, expected {type(expected).__name__}",
    )


def _compare_datetime_fields(
    table: pa.Table,
    row_idx: int,
    eccodes_vals: dict,
    mismatches: list[str],
    msg_idx: int,
    subset_idx: int,
) -> None:
    """Compare date/time fields between earth2bufrio and eccodes.

    earth2bufrio's YEAR/MNTH/DAYS/HOUR/MINU/SECO fixed columns come
    from the BUFR Section 1 (identification), while eccodes' year/month
    etc. come from the data section.  These can legitimately differ, so
    we only compare them when both sides agree (no tolerance for genuine
    discrepancies since they originate from different sections).

    Any mismatch is recorded as informational but does not fail the test
    — it is expected that Section 1 values and data-section values may
    diverge.
    """
    # Intentionally a no-op: datetime fields come from different sources
    # (Section 1 for earth2bufrio, data section for eccodes) and are
    # expected to differ in some files (e.g. uegabe.bufr minute=0 vs 1).
    # A full comparison would need to also read Section 1 from eccodes.


@pytest.mark.integration
@pytest.mark.skipif(not HAS_ECCODES, reason="eccodes not installed")
class TestEccodesCrossval:
    """Cross-validate earth2bufrio Python backend output against eccodes."""

    @pytest.mark.parametrize("fname", WORKING_FIXTURES + XFAIL_FIXTURES)
    def test_crossval_eccodes(self, fname: str) -> None:
        """Compare earth2bufrio output against eccodes reference for a fixture."""
        from earth2bufrio import read_bufr
        from earth2bufrio._tables import TableSet

        bufr_path = DATA_DIR / fname
        ref_data = _load_eccodes_ref(fname)

        # Decode with earth2bufrio
        table = read_bufr(bufr_path)
        tables = TableSet()

        mismatches: list[str] = []

        for msg_ref in ref_data["messages"]:
            msg_idx = msg_ref["message_index"]
            num_subsets = msg_ref["num_subsets"]
            expanded_codes = msg_ref["expanded_codes"]
            expanded_abbrevs = msg_ref["expanded_abbreviations"]

            # Filter 999999 from codes to align with abbreviations
            filtered_codes = [c for c in expanded_codes if c != 999999]
            if len(filtered_codes) != len(expanded_abbrevs):
                mismatches.append(
                    f"msg {msg_idx}: filtered codes ({len(filtered_codes)}) != abbreviations ({len(expanded_abbrevs)})"
                )
                continue

            # Build FXY -> Table B name mapping for earth2bufrio
            fxy_to_e2b_name: dict[int, str] = {}
            for fxy in filtered_codes:
                if fxy not in fxy_to_e2b_name:
                    try:
                        entry = tables.lookup_b(fxy)
                        fxy_to_e2b_name[fxy] = entry.name
                    except KeyError:
                        pass  # Replication/operator descriptors

            # Check subset count matches
            e2b_rows = [
                i
                for i in range(len(table))
                if table.column("message_index")[i].as_py() == msg_idx
            ]
            if len(e2b_rows) != num_subsets:
                mismatches.append(
                    f"msg {msg_idx}: subset count mismatch: earth2bufrio={len(e2b_rows)}, eccodes={num_subsets}"
                )

            # Compare each subset
            for subset_ref in msg_ref["subsets"]:
                subset_idx = subset_ref["subset_index"]
                eccodes_vals = subset_ref["values"]

                # Find the matching earth2bufrio row
                e2b_row_idx = None
                for ri in e2b_rows:
                    if table.column("subset_index")[ri].as_py() == subset_idx:
                        e2b_row_idx = ri
                        break

                if e2b_row_idx is None:
                    mismatches.append(
                        f"msg {msg_idx}, subset {subset_idx}: not found in earth2bufrio output"
                    )
                    continue

                # Compare date/time fixed columns
                _compare_datetime_fields(
                    table,
                    e2b_row_idx,
                    eccodes_vals,
                    mismatches,
                    msg_idx,
                    subset_idx,
                )

                # Compare descriptor values using FXY as bridge.
                # Track occurrences of each e2b column name to handle
                # replicated descriptors that earth2bufrio merges into lists.
                e2b_name_occurrence: dict[str, int] = {}
                abbrev_occurrence: dict[str, int] = {}

                for fxy, abbrev in zip(filtered_codes, expanded_abbrevs, strict=True):
                    # Build the ranked key name that eccodes uses
                    if abbrev not in abbrev_occurrence:
                        abbrev_occurrence[abbrev] = 0
                    abbrev_occurrence[abbrev] += 1
                    rank = abbrev_occurrence[abbrev]
                    ranked_key = abbrev if rank == 1 else f"{abbrev}#{rank}"

                    # Get the eccodes value and normalise missing sentinels
                    raw_ecc_val = eccodes_vals.get(ranked_key)

                    # Skip keys that eccodes could not read (None means
                    # the key errored during generation, not "BUFR missing")
                    if raw_ecc_val is None:
                        continue

                    ecc_val = _normalize_missing(raw_ecc_val)

                    # Look up the earth2bufrio Table B name for this FXY
                    e2b_name = fxy_to_e2b_name.get(fxy)
                    if e2b_name is None:
                        continue  # Operator/replication descriptor, skip

                    # Get earth2bufrio value
                    if e2b_name not in table.column_names:
                        continue  # Column not in output

                    # Track occurrence of this e2b column name
                    if e2b_name not in e2b_name_occurrence:
                        e2b_name_occurrence[e2b_name] = 0
                    e2b_name_occurrence[e2b_name] += 1

                    e2b_val = table.column(e2b_name)[e2b_row_idx].as_py()

                    # Handle replicated descriptors: earth2bufrio merges
                    # repeated descriptors with the same Table B name into
                    # a list. Use the occurrence count to index into the list.
                    e2b_compare_val = e2b_val
                    if isinstance(e2b_val, list) and not isinstance(ecc_val, list):
                        idx = e2b_name_occurrence[e2b_name] - 1
                        e2b_compare_val = e2b_val[idx] if idx < len(e2b_val) else None

                    match, detail = _compare_values(e2b_compare_val, ecc_val)
                    if not match:
                        diff_key = (msg_idx, subset_idx, fxy)
                        known = _KNOWN_DIFFS.get(fname, {}).get(diff_key)
                        if known is None:
                            mismatches.append(
                                f"msg {msg_idx}, subset {subset_idx}, "
                                f"fxy={fxy:06d} ({e2b_name} / {ranked_key}): "
                                f"{detail}"
                            )

                    if len(mismatches) >= 50:
                        break
                if len(mismatches) >= 50:
                    break
            if len(mismatches) >= 50:
                break

        if mismatches:
            detail = "\n".join(mismatches[:50])
            total = len(mismatches)
            pytest.fail(
                f"{total} mismatches in {fname}:\n{detail}"
                + (f"\n... and {total - 50} more" if total > 50 else "")
            )
